[package]
name = "blindsign"
version = "0.1.0"
authors = ["boojies"]

[dev-dependencies]
sha3 = "0.7.3"

[dependencies]
digest = "0.7.2"
rand = "0.5.0"
failure = "0.1.1"
failure_derive = "0.1.1"
typenum = "1.10.0"

[dependencies.curve25519-dalek]
version = "^0.17"
features = ["nightly"]
